[tool.poetry]
name = "aula-08"
version = "0.1.0"
description = "aula08"
authors = ["c"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pandas = "^2.2.2"
pandera = "^0.18.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
